config/routes.rb
Rails.application.routes.draw do

  resources :countries

  resources :document_types

  root to: 'visitors#index'

  devise_for :users, controllers: { sessions: "user/sessions", registrations: "user/registrations" }
  
  resources :users

  resources :developer do
    member do
      post "edit_skill"
      post "edit_project"
      get "new_developer_skill"
      post "create_developer_skill"
      post "delete_developer_skill"
      get "new_developer_project"
      post "create_developer_project"
      post "delete_developer_project"
      post "developer_profile"
    end
  end  

  resources :skill

  resources :project do
    collection do
      get "developer_projects"
     end 
  end  

  resources :client

  post '/search_skills/search/', to: 'search_skills#search'


  resources :search_skills do
     member do
      post 'search'
    end
  end  

  resources :developer do
    resources :developer_has_skills
  end

  resources :developer do
    resources :developer_has_projects
  end

  resources :project do
    resources :project_has_skills
  end

end

app/controllers/developer_controller.rb
class DeveloperController < ApplicationController
	before_filter :authenticate_user!
  before_action :set_current_project, only:[:create_developer_project, :edit_project]


  def index
  	 @developers = Person.all
  end

  def new
     @developer = Person.new
  end


  def create
    @developer = Person.new(secure_params)
    if @developer.save
      redirect_to developer_index_path , :notice => "Developer Created!"
    else
      render :action => 'new'
    end
  end


  def edit
  	 @developer      = Person.find(params[:id])
	 @document_types = DocumentType.all
  end


  def update
  	 @developer = Person.find(params[:id])
    if @developer.update_attributes(secure_params)
      
      respond_to do |format|
        format.html{redirect_to developer_index_path, :notice => "Developer updated."}
        format.json { render json: @developer }
      end
    else
      respond_to do |format|
        format.html {render :action => 'edit'}
        format.json { render json: @developer.errors, :status => 500 }
      end
    end
  end


  def show
    @developer = Person.find(params[:id])
    @skill_language = Skill.languages
    @skill_framework = Skill.framework
    @skill_mobile = Skill.mobile
    @skill_database = Skill.database

    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
    respond_to do |format|
        format.html {render :action => :show}
        format.pdf { 
          render pdf: "developer_profile",template:'developer/developer_profile.pdf.erb',show_as_html: params[:debug]
        }
      end
  end

  def developer_profile
    
    @developer = Person.find(params[:id])
    unless params[:rating].empty?
    
    @person_language_skill = @developer.person_language_skill.where('rating >= ?', params[:rating])
    @person_framework_skill = @developer.person_framework_skill.where('rating >= ?', params[:rating])
    @person_data_skill = @developer.person_data_skill.where('rating >= ?', params[:rating])
    @person_mobile_skill = @developer.person_mobile_skill.where('rating >= ?', params[:rating])
    else
    @person_language_skill = @developer.person_language_skill
    @person_framework_skill = @developer.person_framework_skill
    @person_data_skill = @developer.person_data_skill
    @person_mobile_skill = @developer.person_mobile_skill
    end 

    unless params[:start_date].empty?
      @developer_project =  @developer.person_has_projects.where('start_date >= ? ',params[:start_date])
      else
      @developer_project =  @developer.person_has_projects  
    end
    
    
    respond_to do |format|
      format.pdf { 
             render pdf: "#{@developer.full_name}_profile",
             disposition: 'attachment',
             template:'developer/developer_profile.pdf.erb',
             save_to_file: Rails.root.join('public/assets/pdf', "#{@developer.full_name}_profile.pdf")
             
      }
    end  
  end  


  def edit_skill
    @developer_skill = PersonHasSkill.find(params[:person_has_skill_id])
    @skill = Skill.find(params[:person_has_skill][:skill_id])
    @skill_language = case @skill[:skill_type].to_i
                   when 0
                      Skill.languages
                    when 1  
                      Skill.framework
                    when 2 
                      Skill.database
                    when 3
                      Skill.mobile
                   end               
    if @developer_skill.update_attributes(secure_params_developer_skill)
      respond_to do |format|
         format.js
      end
    end  
  end


  def edit_project
    @developer_project = PersonHasProject.find(params[:person_has_project_id])
    if @developer_project.update_attributes(secure_params_developer_project)
      respond_to do |format|
         format.js
      end
    end  
  end  

  def new_developer_skill
     @developer = Person.find(params[:id])
     developer_skills_list = PersonHasSkill.where('person_id = ?', params[:id])
     @developer_available_skills = Skill.where('id not in (?)', developer_skills_list.map(&:skill_id).empty? ? 0 :  developer_skills_list.map(&:skill_id))
     @developer_skill = PersonHasSkill.new
     respond_to do |format|
         format.js
     end
  end

  def new_developer_project
    @developer = Person.find(params[:id])
    @developer_projects = PersonHasProject.list_developer_projects(params[:id])
    @developer_available_projects = Project.where('id not in (?)', @developer_projects.map(&:project_id).empty? ? 0 : @developer_projects.map(&:project_id))
    @current_projects = @developer_projects.current_projects
    @developer_project = PersonHasProject.new
    respond_to do |format|
         format.js
     end
  end  

  def create_developer_skill
    @developer_skill = PersonHasSkill.new(secure_params_developer_skill)
    @skill = Skill.find(params[:person_has_skill][:skill_id])
    @developer_skill.person_id = params[:id]
    @developer = Person.find(params[:id])
    @person_skill_language = case @skill[:skill_type].to_i
                   when 0
                      @developer.person_language_skill
                    when 1  
                      @developer.person_framework_skill
                    when 2 
                      @developer.person_data_skill
                    when 3
                      @developer.person_mobile_skill
                   end
    if @developer_skill.save
        flash.now[:notice] = "Skill Association Created!"
    else
     render :json => @developer_skill.errors, :status => 500
    end  
  end  

  def create_developer_project
    @developer_project = PersonHasProject.new(secure_params_developer_project)
    @developer_project.person_id = params[:id]
    @developer = Person.find(params[:id])
    if @developer_project.save
      flash.now[:notice] = "Project Association Created!"
    else
      render :json => @developer_project.errors, :status => 500
    end  
  end  

  def destroy
  	developer = Person.find(params[:id])
  	developer.destroy
  	redirect_to developer_index_path, :notice => "Developer deleted."
  end

  def delete_developer_skill
    developer_skill = PersonHasSkill.find(params[:person_has_skill])
    developer_skill.destroy
  end  

  def delete_developer_project
    developer_project = PersonHasProject.find(params[:person_has_project])
    developer_project.destroy
  end
    
  private
  def secure_params
    params.require(:person).permit(:name, :last_name, :email, :cel_number , :home_number,:address, :country_id, :document_type_id, :id_number, :birth_day, :image, :skype)
  end

  def secure_params_developer_skill
    params.require(:person_has_skill).permit(:person_id, :skill_id, :rating, :projects, :note)
  end
  
  def secure_params_developer_project
    params.require(:person_has_project).permit(:person_id, :project_id, :start_date, :finish_date, :note, :current_project, :developer_condition)
  end  

end

app/helpers/developer_helper.rb
module DeveloperHelper
	def get_skill_type(skill_type)
		skill_clase = case skill_type.to_i
		when 0
			'tbody_language-skill'
		when 1
			'tbody_framework-skill'	
		when 2
			'tbody_data-skill'
		when 3
		    'tbody_mobile-skill'		
		end
	end	

	def show_current_project(bool)
		if bool == true
		  label_tag nil, 'current', class: 'label badge'
	    end	
	end	
end

app/views/developer/_developer_project.html.erb
<div id="show_developer_project">
<h3>Projects <%=link_to image_tag("/assets/images/add32.png", :class => 'developer_icon', :alt => '', :title => '', width: 24, height: 24),'javascript:',:class => 'developer_edit',:id => "add-developer-project" %></h3> 

<ul class="nav nav-pills" id="skill_tab">
       <li role="presentation" class="active"><a id="account_tab" href="#account" role="tab" data-toggle="tab" aria-controls="account" aria-expanded="true">Accounts</a></li>
       <!-- <li role="presentation"><a id="internal_tab" href="#internal" role="tab" data-toggle="tab" aria-controls="internal" aria-expanded="true">Internals</a></li> -->
</ul>
<div class="tab-content">
    	<div role="tabpanel" class="project-tabpanel tab-pane fade active in" id="account" aria-labelledby="account-tab">
    		<table class="table" id="project-projets">
                <tbody id="tbody_project-projets">
    			<% @developer.person_has_projects.each do |project|%>

    			<tr id="project_show<%=project.id%>" data-date="<%= project.finish_date%>">
    				<td class="col-xs-2"><%=project.project.name%></td>
    				<td><%=project.start_date.strftime("%b %d, %Y")%></td>
    				<td><%= project.finish_date.try(:strftime, "%b %d, %Y")%></td>
    				<td>
                        <%=link_to image_tag("/assets/images/edit_16.png", :class => 'developer_icon', :alt => '', :title => ''),
                     'javascript:',:class => 'project_edit',:id => "#{project.id}" %>
                     <%= link_to image_tag("/assets/images/delete_16.png", :class => 'developer_icon', :alt => '', :title => ''),
                     'javascript:',:class => 'delete-developer-project',:id => "#{project.id}"%>
                     <%= show_current_project(project.current_project)%>
                 </td>
    			</tr>
    			<tr id="project_edit<%=project.id%>" class="hide" data-date="<%= project.finish_date%>">
    				<td class="col-xs-2"><%=project.project.name%></td>
    				<td class="col-xs-2"><%=date_field("project_has_skill#{project.id}", "start_date",{value: project.start_date, class: "form-control"} )%></td>
    				<td class="col-xs-2"><%=date_field("project_has_skill#{project.id}", "finish_date",{value: project.finish_date, class: "form-control"} )%></td>
    				<td>
<%= check_box_tag("current_project#{project.id}", project.current_project, project.current_project)%>
    					<%= link_to("update", "javascript:",{class: " update-developer-project btn btn-primary btn-xs", data: { id:"#{project.id}"}})%>
                            <button data-id="<%=project.id%>" type="button" class="btn btn-danger btn-xs btn-project-cancel">cancel</button>
    				</td>
    			</tr>	
    			<% end%>
             </tbody>
    		</table>	
        </div>
</div>
</div>	

app/views/developer/_developer_skill.html.erb
<div id="show_developer_skill">

	<h3>Skills <%=link_to image_tag("/assets/images/add32.png", :class => 'developer_icon', :alt => '', :title => '', width: 24, height: 24),
                     'javascript:',:class => 'developer_edit',:id => "#{@developer.could_add_skill ? 'add-skill' : 'message-skill'}" %>
    </h3> 
   
	<ul class="nav nav-pills" id="skill_tab">
       <li role="presentation" class="active"><a id="technology_tab" href="#language" role="tab" data-toggle="tab" aria-controls="language" aria-expanded="true">Languages</a></li>
       <li role="presentation"><a id="framework_tab" href="#framework" role="tab" data-toggle="tab" aria-controls="framework" aria-expanded="true">Frameworks</a></li>
       <li role="presentation"><a id="mobile_tab" href="#mobile" role="tab" data-toggle="tab" aria-controls="mobile" aria-expanded="true">Mobiles</a></li>
       <li role="presentation"><a id="data_tab" href="#data" role="tab" data-toggle="tab" aria-controls="data" aria-expanded="true">DataBases</a></li>
    </ul>
    <div class="tab-content">
    	<div role="tabpanel" class="developer-tabpanel tab-pane fade active in" id="language" aria-labelledby="language-tab">
    		<table class="table" id="language-skill">
                <tbody id="tbody_language-skill">
    			<% @developer.person_language_skill.each do |skill|%>
    			<tr id="show_<%=skill.id%>" data-rating="<%=skill.person_has_skills.person_attributes(@developer.id).rating %>">
                    <td><%=skill.name%></td> <td><%= skill_badge(skill.person_has_skills.person_attributes(@developer.id).rating) %></td>
                    <td><%=link_to image_tag("/assets/images/edit_16.png", :class => 'developer_icon', :alt => '', :title => ''),
                     'javascript:',:class => 'developer_edit',:id => "#{skill.id}" %>
                     
                        <%= link_to image_tag("/assets/images/delete_16.png", :class => 'developer_icon', :alt => '', :title => ''),
                     'javascript:',:class => 'delete-developer-skill',:id => "#{skill.person_has_skills.person_attributes(@developer.id).id}",data: { id:"#{skill.id}"}%>
                     </td>
                    </tr>
                    <tr class="hide" id="edit_<%=skill.id%>" data-rating="<%=skill.person_has_skills.person_attributes(@developer.id).rating %>">
                        <td>
                            <%=skill.name%>
                        </td>
                        <td><%= select_tag("rating", options_for_select(PersonHasSkill.skill_ratings.map {|key, id| [id, id] },skill.person_has_skills.person_attributes(@developer.id).rating),{id: "rating#{skill.id}" })%>
                            <%= hidden_field_tag 'person_has_skill_id', skill.person_has_skills.person_attributes(@developer.id).id, {id: "person_has_skill_id#{skill.id}"} %>
                        </td>
                            
                        <td>
                            <%= link_to("update", "javascript:",{class: " update-developer-skill btn btn-primary btn-xs", id: "update_#{skill.id}",data: { id:"#{skill.id}"}})%>
                            <button data-id="<%=skill.id%>" type="button" class="btn btn-danger btn-xs btn-cancel">cancel</button>    
                        </td>
                    </tr>
    			<% end%>
            </tbody>
    		</table>
    	</div>
    	<div role="tabpanel" class="developer-tabpanel tab-pane fade" id="framework" aria-labelledby="framework-tab">
    		<table class="table" id="framework-skill">
                <tbody id="tbody_framework-skill">
    			<% @developer.person_framework_skill.each do |skill|%>
    			<tr id="show_<%=skill.id%>" data-rating="<%=skill.person_has_skills.person_attributes(@developer.id).rating %>">
                    <td><%=skill.name%></td> <td><%= skill_badge(skill.person_has_skills.person_attributes(@developer.id).rating) %></td>
                    <td><%=link_to image_tag("/assets/images/edit_16.png", :class => 'developer_icon', :alt => '', :title => ''),
                     '#',:class => 'developer_edit',:id => "#{skill.id}" %>
                        <%= link_to image_tag("/assets/images/delete_16.png", :class => 'developer_icon', :alt => '', :title => ''),
                     'javascript:',:class => 'delete-developer-skill',:id => "#{skill.person_has_skills.person_attributes(@developer.id).id}",data: { id:"#{skill.id}"}%>
                     </td>
                    </tr>
                    <tr class="hide" id="edit_<%=skill.id%>" data-rating="<%=skill.person_has_skills.person_attributes(@developer.id).rating %>">
                        <td>
                            <%=skill.name%>
                        </td>
                        <td><%= select_tag("rating", options_for_select(PersonHasSkill.skill_ratings.map {|key, id| [id, id] },skill.person_has_skills.person_attributes(@developer.id).rating),{id: "rating#{skill.id}" })%>
                            <%= hidden_field_tag 'person_has_skill_id', skill.person_has_skills.person_attributes(@developer.id).id, {id: "person_has_skill_id#{skill.id}"} %>
                        </td>
                        <td>
                            <%= link_to("update", "javascript:",{class: " update-developer-skill btn btn-primary btn-xs", id: "update_#{skill.id}",data: { id:"#{skill.id}"}})%>
                            <button data-id="<%=skill.id%>" type="button" class="btn btn-danger btn-xs btn-cancel">cancel</button>    
                        </td>
                    </tr>
    			<% end%>
            </tbody>
    		</table>
    	</div>
    	<div role="tabpanel" class="developer-tabpanel tab-pane fade" id="mobile" aria-labelledby="mobile-tab">
    		<table class="table" id="mobile-skill">
                <tbody id="tbody_mobile-skill">
    			<% @developer.person_mobile_skill.each do |skill|%>
    			<tr id="show_<%=skill.id%>" data-rating="<%=skill.person_has_skills.person_attributes(@developer.id).rating %>">
                    <td><%=skill.name%></td> <td><%= skill_badge(skill.person_has_skills.person_attributes(@developer.id).rating) %></td>
                    <td><%=link_to image_tag("/assets/images/edit_16.png", :class => 'developer_icon', :alt => '', :title => ''),
                     '#',:class => 'developer_edit',:id => "#{skill.id}" %>
                        <%= link_to image_tag("/assets/images/delete_16.png", :class => 'developer_icon', :alt => '', :title => ''),
                     'javascript:',:class => 'delete-developer-skill',:id => "#{skill.person_has_skills.person_attributes(@developer.id).id}",data: { id:"#{skill.id}"}%>
                     </td>
                    </tr>
                    <tr class="hide" id="edit_<%=skill.id%>" data-rating="<%=skill.person_has_skills.person_attributes(@developer.id).rating %>">
                        <td>
                            <%= skill.name%>
                        </td>
                        <td><%= select_tag("rating", options_for_select(PersonHasSkill.skill_ratings.map {|key, id| [id, id] },skill.person_has_skills.person_attributes(@developer.id).rating),{id: "rating#{skill.id}" })%>
                            <%= hidden_field_tag 'person_has_skill_id', skill.person_has_skills.person_attributes(@developer.id).id, {id: "person_has_skill_id#{skill.id}"} %>
                        </td>
                        <td>
                            <%= link_to("update", "javascript:",{class: " update-developer-skill btn btn-primary btn-xs", id: "update_#{skill.id}",data: { id:"#{skill.id}"}})%>
                            <button data-id="<%=skill.id%>" type="button" class="btn btn-danger btn-xs btn-cancel">cancel</button>   
                        </td>
                    </tr>
    			<% end%>
            </tbody>
    		</table>
    	</div>
    	<div role="tabpanel" class="developer-tabpanel tab-pane fade" id="data" aria-labelledby="data-tab">
    		<table class="table" id="data-skill">
                <tbody ="tbody_data-skill">
    			<% @developer.person_data_skill.each do |skill|%>
    			<tr id="show_<%=skill.id%>" data-rating="<%=skill.person_has_skills.person_attributes(@developer.id).rating %>">
                    <td><%=skill.name%></td> <td><%= skill_badge(skill.person_has_skills.person_attributes(@developer.id).rating) %></td>
                    <td><%=link_to image_tag("/assets/images/edit_16.png", :class => 'developer_icon', :alt => '', :title => ''),
                     '#',:class => 'developer_edit',:id => "#{skill.id}" %>
                        <%= link_to image_tag("/assets/images/delete_16.png", :class => 'developer_icon', :alt => '', :title => ''),
                     'javascript:',:class => 'delete-developer-skill',:id => "#{skill.person_has_skills.person_attributes(@developer.id).id}",data: { id:"#{skill.id}"}%>
                     </td>
                    </tr>
                    <tr class="hide" id="edit_<%=skill.id%>" data-rating="<%=skill.person_has_skills.person_attributes(@developer.id).rating %>">
                        <td>
                            <%= skill.name%>
                        </td>
                        <td><%= select_tag("rating", options_for_select(PersonHasSkill.skill_ratings.map {|key, id| [id, id] },skill.person_has_skills.person_attributes(@developer.id).rating),{id: "rating#{skill.id}" })%>
                            <%= hidden_field_tag 'person_has_skill_id', skill.person_has_skills.person_attributes(@developer.id).id, {id: "person_has_skill_id#{skill.id}"} %>
                        </td>
                        <td>
                            <%= link_to("update", "javascript:",{class: " update-developer-skill btn btn-primary btn-xs", id: "update_#{skill.id}",data: { id:"#{skill.id}"}})%>
                            <button data-id="<%=skill.id%>" type="button" class="btn btn-danger btn-xs btn-cancel">cancel</button>    
                        </td>
                    </tr>
    			<% end%>
            </tbody>
    		</table>
    	</div>
    </div>	
</div>	

app/views/developer/edit.html.erb
<div class="authform_large">
 <%= form_for(@developer, :url => developer_path(@developer.id), :html => { :method => :put, :role => 'form', :multipart => true}) do |f| %>
    <div class="col-md-12">
      <%= devise_error_messages! %>
      <% if @developer.errors.any? %>
        <div id="error_explanation">
        <ul>
            <% @developer.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
             </ul>
        </div>
        <% end %>
       <h3>Edit a New Developer</h3>
    </div>
  <div class="row">
    <div class="col-md-6">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :address %>
          <%= f.text_area :address, :rows => 3,  class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :home_number %>
          <%= f.text_field :home_number, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :cel_number %>
          <%= f.text_field :cel_number, class: 'form-control' %>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
        <%= f.label :skype %>
        <%= f.text_field :skype, class: 'form-control' %>
      </div>
        <div class="form-group">
            <%= f.label :Country %> </br>
            <%= f.collection_select(:country_id, Country.all, :id, :name, {:prompt=>true},{ class: 'form-control'}) %>
        </div>
        <div class="form-group">
            <%= f.label :Document_Type %> </br>
            <%= f.collection_select(:document_type_id, DocumentType.all, :id, :name, {:prompt=>true},{ class: 'form-control'}) %>
        </div>
        <div class="form-group">
          <%= f.label :Identification_Number %>
          <%= f.text_field :id_number, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :Birth_Day %>
          <%= f.date_field :birth_day, class: 'form-control' %>
        </div>
        <fieldset>
        <% unless @developer.image_file_name.blank? %>
          <div class="form-group">
              You have already a Image:
              <br>
             <%= image_tag @developer.image.url(:thumb) %>
              <br>
              If you want another:
          </div>
        <% end %>
          <div class="form-group">
            <%= f.label :Developer_Image %>
            <%=  f.file_field :image %>
          </div>
        </fieldset>
    </div>
    <div class="col-md-12 text-right">
      <%= f.submit 'Update Developer', :class => 'btn btn-primary' %>
    </div>
  </div>
  <% end %>
</div>

app/views/developer/index.html.erb
<div class="container">
  <div class="row">
    <h3>Developers</h3>
     <div class="row text-right"><%= link_to(" + Create New Developer", new_developer_path, :method => :get, :class => 'button-xs') %></div>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Actions</th>
            </tr>
          </thead>  
          <tbody>
            <% @developers.each_with_index do |developer, i| %>
              <tr>
                <th scope="row"><%= i + 1%></th>
                <td>
    					<%= link_to developer.name.to_s + ' ' + developer.last_name.to_s, developer_path(developer) %> 
      				</td>
      				<td>
                <%= link_to("Manage Projects", developer_developer_has_projects_path(developer), :class => 'button-xs btn-warning') %>
                <%= link_to("Manage Skills", developer_developer_has_skills_path(developer), :class => 'button-xs btn-success') %>
      				  <%= link_to("Edit", edit_developer_path(developer), :method => :get, :class => 'button-xs') %>
      				  <%= link_to("Delete", developer_path(developer), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs btn-danger') %>
      				</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

app/views/developer/show.html.erb
<div class="container">
	<div class="row">
		<%= hidden_field_tag 'developer_id', @developer.id, {id: "developer_id"} %>
		<table>
			<tr>
				<td>
					<%= image_tag(get_developer_image(@developer.image_file_name,@developer.id))%>
				</td>
				<td> <table>	
					 <tr>
						 <td>	
					      <h3><span id="edit_name"><%= @developer.full_name%></span>
					      	<%=link_to image_tag("/assets/images/edit_16.png", :class => 'developer_icon', :id => 'change_edit', :title => ''),
                     'javascript:',:class => 'edit-developer',:id => "#{@developer.id}" %>

                     <%=link_to image_tag("/assets/images/4pdf-16.png", :class => 'developer_icon', :id => '', :title => ''),'javascript:',:class => 'developer-export',:id => "pdf_export" %>
					      </h3>
					     </td>
				     </tr> 
				     <tr><td><img class = "developer_icon" src="/assets/images/mail_16.png" />
				     	<span id="edit_email"><%= @developer.email%></span></td></tr>
				     <tr><td><img class = "developer_icon" src="/assets/images/skype_16.png" />
				     	<span id="edit_skype"><%= @developer.skype%></span>
				     </td></tr>
				     <tr><td><img class = "developer_icon" src="/assets/images/old20.png" />
				     	<span id="edit_home_number"><%= @developer.home_number%><span></td></tr>
				 </table>
				</td>
			</tr>
		</table>

		<div class="container">

			<%= render 'developer_skill' %>	
			<%= render 'developer_project' %>	
		</div>

	</div>
	<div id="show-new-developer-skill"></div>
	<div id="show-new-developer-project"></div>

	<div id="no-add" class="modal fade" aria-hidden="true" role="dialog">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title">Messages</h4>
	      </div>
	      <div class="modal-body">
	        <p id="developer-message"></p>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      </div>
	    </div>
	  </div>
	</div>

	<div id="pdf-profile" class="modal fade" aria-hidden="true" role="dialog">
		<div class="modal-dialog">
	      <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title">Export Profile</h4>
	      </div>
	      <%= form_tag(developer_profile_developer_path(@developer), method: "post",id: 'exportsubmit') do %>
	      <div class="modal-body">
		        <div class="col-md-12">

			        <div class="form-group"></br>
		                <%= label_tag :Skill_Level %> </br>
		                <%= select_tag(:rating, options_for_select(PersonHasSkill.skill_ratings.map {|key, id| [key.titleize, id ]}) ,{include_blank: true, class:  'form-control'})  %>
		            </div>
		            <div class="form-group">
			          <%= label_tag :start_date  %>
			          <%= date_field_tag :start_date,nil ,class: 'form-control' %>
			          <%= hidden_field_tag 'format', 'pdf'%>
			         </div>
		        </div>    
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <button id="export-developer-profile" type="button" class="btn btn-primary">Save</button>
	      </div>
	      <% end %>
	    </div>
	  </div>

	</div>

</div>